import '../modelos/animal.dart';

final List<Animal> animalesMock = [
  Animal(
    id: '1',
    nombre: 'Max',
    especie: 'Perro',
    raza: 'Golden Retriever',
    edad: 2,
    sexo: 'Macho',
    descripcion: 'Max es un perro muy sociable y activo. Le encanta jugar con niños y otros perros. Está perfectamente adaptado a la vida en familia. Busca un hogar con jardín o cerca de zonas verdes para poder correr y disfrutar.',
    imagenUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400',
    disponible: true,
    peso: '28 kg',
    vacunado: true,
    esterilizado: false,
    microchip: true,
    refugio: 'Refugio Esperanza Madrid',
    ubicacionRefugio: 'Madrid, España',
  ),
  Animal(
    id: '2',
    nombre: 'Oreo',
    especie: 'Gato',
    raza: 'Gato Europeo',
    edad: 1,
    sexo: 'Hembra',
    descripcion: 'Oreo es una gatita juguetona y muy cariñosa. Se lleva fenomenal con otros animales y con niños. Le encanta explorar cada rincón de la casa y ronronear en el sofá.',
    imagenUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
    disponible: true,
    peso: '3.5 kg',
    vacunado: true,
    esterilizado: true,
    microchip: false,
    refugio: 'Protectora Los Animales',
    ubicacionRefugio: 'Barcelona, España',
  ),
  Animal(
    id: '3',
    nombre: 'Luna',
    especie: 'Gato',
    raza: 'Siamés',
    edad: 3,
    sexo: 'Hembra',
    descripcion: 'Luna es una gata tranquila y elegante. Perfecta para hogares tranquilos donde pueda descansar y recibir mimos. Se adapta bien a pisos pequeños.',
    imagenUrl: 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=400',
    disponible: true,
    peso: '4 kg',
    vacunado: true,
    esterilizado: true,
    microchip: true,
    refugio: 'Refugio Esperanza Madrid',
    ubicacionRefugio: 'Madrid, España',
  ),
  Animal(
    id: '4',
    nombre: 'Rocky',
    especie: 'Perro',
    raza: 'Labrador',
    edad: 4,
    sexo: 'Macho',
    descripcion: 'Rocky es un perro leal y obediente. Ideal para familias con niños. Le encanta el agua y los paseos largos. Está bien entrenado y responde a órdenes básicas.',
    imagenUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    disponible: true,
    peso: '32 kg',
    vacunado: true,
    esterilizado: false,
    microchip: true,
    refugio: 'Protectora Los Animales',
    ubicacionRefugio: 'Valencia, España',
  ),
  Animal(
    id: '5',
    nombre: 'Nala',
    especie: 'Perro',
    raza: 'Beagle',
    edad: 1,
    sexo: 'Hembra',
    descripcion: 'Nala es una cachorra curiosa y llena de energía. Le encanta explorar y jugar. Necesita un hogar activo que le dé el ejercicio y el cariño que merece.',
    imagenUrl: 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=400',
    disponible: true,
    peso: '8 kg',
    vacunado: false,
    esterilizado: false,
    microchip: false,
    refugio: 'Refugio Esperanza Madrid',
    ubicacionRefugio: 'Sevilla, España',
  ),
];